### ISSUE TITLE
Buzzing sound continues after stopping playback

### ISSUE THREAD

**Issue by bhagerty** [csound/web-ide#149]
On Windows 10, using Chrome Version 84.0.4147.135 (Official Build) (64-bit), I am getting a loud buzzing sound when I stop playback of a project. I have tried three separate projects with the same result: [Bossa Nooo](https://ide.csound.com/editor/RjWhJ65fYz9luQnR2jY2), [Blue89](https://ide.csound.com/editor/gl2UHUvRjAhiKKkY3yiF), and [A Little Blue](https://ide.csound.com/editor/3Dvmip3688eEqVMxVF5z). The sound stops when I start playback again. The sound volume and pitch change when I start and stop playback. The sound stops if I refresh the page.  

I am not sure what else I could tell you for diagnosis purposes.

**Comment by kunstmusik** [comment]
This is a duplicate of #102. The bug was in Chrome itself and was fixed in Chrome 85 which is now available.
