### ISSUE TITLE
Console log gets full and slows down site

### ISSUE THREAD

**Issue by kunstmusik** [csound/web-ide#28]
Console log when running csound can get very full and slow if project is printing alot. Need a solution for limiting length of log and consider memory.

**Comment by hlolli** [comment]
Can you test latest develop and see if the virtualized list solved this?

**Comment by kunstmusik** [comment]
I did a test here and performance was good. I printed a lot of messages and
the system got a little behind in adding the messages to the console, but
not sure where that issue is coming from. The page as a whole still
operated well though. I noticed no scrollbar to help see where you are when
scrolling; is that something hard to add?

**Comment by hlolli** [comment]
I tested with 20 seconds of 0.01 sec printk, and I didn't experience that the logs were behind, on the other hand, the draggable scrollbar size became incredibly small very quiickly, I need to add some min-size for it to be visible.

**Comment by hlolli** [comment]
Oh wait, I see it now, the scrollbar disappeared after I resized the resizeable window. Will investigate.

**Comment by hlolli** [comment]
I abandoned perfect-scrollbar here, since I can't use the react version due to strange nesting from virtualized list, I falled back to use native scrollbar with some css styling to make it look a bit better. So the scrollbar should never disappear now.

**Comment by kunstmusik** [comment]
Working well here now. Only issue I see is if the console is printing out a
lot of messages it's hard to scroll back while things are appending.  I
think we can close this and take that up in another issue.
