### ISSUE TITLE
Auth: User can create new account 

### ISSUE THREAD

**Issue by kunstmusik** [csound/web-ide#4]
* Use FirebaseUI
* Sign-up directly
* Sign-up via 3rd party signin providers

**Comment by hlolli** [comment]
Mostly done, https://github.com/csound/web-ide/commit/f0b1b28b0e4509c91b244363b28c9ebff158f0bd
with facebook auth ready, it'll be ready.

**Comment by hlolli** [comment]
Cleanup, this issue is solved already.
