### ISSUE TITLE
Scrolling in Console not easy when appending

### ISSUE THREAD

**Issue by kunstmusik** [csound/web-ide#41]
When messages are appending to the console it's not easy to scroll. Might be nice to be able to have console only automatically scroll when the scrollbar is at the end position, otherwise the scroll position stays.

**Comment by hlolli** [comment]
After the changes I did last night, the Console behaves like any other termnal where the position follows the new elements being appended, and is in full user control when the user scrolls up away from the bottom. I worry a bit if there's enough margin between the bottom and  the latest console line. But maybe you have a look and close this ticket if that makes sense?

**Comment by hlolli** [comment]
closing since we had a look at this togeather in Ireland, the bottom visibility could still be improved, that would be unrelated to this ticket.
