### ISSUE TITLE
Fix error to at least show site for iOS devices

### ISSUE THREAD

**Issue by kunstmusik** [csound/web-ide#48]
Exceptions are currently thrown for iOS devices and the site comes up as a white screen.

**Comment by hlolli** [comment]
just tested with BrowserStack and safari iOS seems to report

```
TypeError: undefined is not a constructor (evaluating 'new
window.ResizeObserver(t)')
```

we are probably fine with just adding

https://www.npmjs.com/package/resize-observer-polyfill

**Comment by csounder** [comment]
> Exceptions are currently thrown for iOS devices and the site comes up as a white screen.

I think that you might have fixed this!  It is now working on my iPhone.

**Comment by csounder** [comment]
Also now working on iPad!  I think that the bug is fixed.

**Comment by hlolli** [comment]
perfect @csounder thanks for reporting!
