### ISSUE TITLE
RealTime PlayBack from iPhone doesn’t work

### ISSUE THREAD

**Issue by csounder** [csound/web-ide#53]
on iPad, realtime audio playback does work, but on the iPhone, real-time audio playback does not work.

**Comment by kunstmusik** [comment]
I'd check if notifications is turn off on the iPhone. iOS has a known issue
where webaudio will go silent if notifications is off (even though web
<video> tags still will still play audio!).

**Comment by hlolli** [comment]
interesting, I'll test for it as well tonight, I wonder if we can detect this and notify the user to change their notification setting (which in iPhone's case is just a switch on the phone itself).

**Comment by hlolli** [comment]
oh yeh, that is indeed the case, I got audio from my iphone by just flipping the switch on my device.

**Comment by kunstmusik** [comment]
That issue with iOS cost me a lot of time a couple years ago when I was
testing WebAudio Csound and wondering why I wasn't hearing anything. ;) I
am not aware of a way to detect it myself, but I haven't looked into it
since.

**Comment by csounder** [comment]
Happy to report that real-time audio does work on the iPhone!  Thanks for the tip.

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by hlolli** [comment]
I also added a one time warning about the notification switch for iOS clients.
