### ISSUE TITLE
Pausing Playback - can’t unPause

### ISSUE THREAD

**Issue by csounder** [csound/web-ide#54]
On iPad, if you hit the render/play arrow, the sound begins to play, BUT... if you touch the pause button while it is playing, the sound pauses, but one cannot unPause.  Or play anything else.  One has to restart to browser and login again to get the audio to work again.

**Comment by csounder** [comment]
Note - this does work correctly on a MacBook Pro.  Not on iPhone and iPad.

**Comment by hlolli** [comment]
I just tested on iPad, and pausing/playing works. I believe this bug was related to another bug which I just fixed, where stopping a playback wasn't possible under certain circumstances.
