### ISSUE TITLE
Question - How to get Steven Yi's Featured Project - Csound Live Code to Render?

### ISSUE THREAD

**Issue by csounder** [csound/web-ide#82]
I assume that live.csound is running from within the Csound Web-IDE and so, I would love to try out and hear Steven Yi's featured live-coding project, but I do not know how to "evaluate" it and render it?

**Comment by hlolli** [comment]
The trick is to start it by pressing the play button, then while running, you can evaluate instuments blocks, by placing the cursor anythere within an instr block, and press on the keyboard "ctrl+enter" maybe it's "command+enter" on macOs.

**Comment by csounder** [comment]
Thanks.  I did try that.  I will try again. That might be the problem, the shortcut might not be working on the Mac or the same.  

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by csounder** [comment]
Well there are still issues with Steven's "Popular" example/model.

First:  I love it.  and I love his live.csound work!  BUT - that is when it works!

Here are the issues:  

1 - hit the arrow, like all the other popular examples, and nothing happens!
- Others actually render the project and make a sound - this gives the impression it is not working.

2. There are no instructions on how to make something happen (or indicate that it will only make sound if you do this and this and this... etc.

3. To get this to work, on a Mac, one needs to
A.  Open project
B.  Select project.csd
C.  Run Csound (and still hear nothing)
D. Switch to Practice_Session.orc
E.  Select entire Practice session (highlight it)
F.  Hit "ctrl e". (Not even sure that "ctrl-enter" works) in order to evaluate the entire selected .orc and hear something

Then you can, for instance - change the tempo, and evaluate a single line while the live code is running (with a "ctrl-e")

And... no hints or command-key help appears when you open someone else's project.

**Comment by kunstmusik** [comment]
Closing this; this is a part of live coding with a project. There's shortcut information in the help menu.  We can add more to documentation but putting my name into an issue isn't useful.
