### ISSUE TITLE
cannot reset password or create a new account

### ISSUE THREAD

**Issue by zappfinger** [csound/web-ide#93]
I tried to log in, but no luck, so I tried reset password. That did not work. Maybe I had not created an account so then I tried to create one. Nothing happened. If I had already an account I would expect a message about that...

**Comment by tgrey1** [comment]
I can't *really* help with this, but can you add some info about OS version, browser version, etc for those that can?  Thanks!

**Comment by zappfinger** [comment]
Ok, this is on Mac OS X. 10.13.4 in the Chrome browser (Version 83.0.4103.61 (Official Build) (64-bit))

**Comment by kunstmusik** [comment]
The reset password should already be working; the create new user flow had an issue where it was reading from the wrong data fields.  The fix is pushed and this should be deploying shortly. Thanks for reporting this @zappfinger!
