### ISSUE TITLE
"Configure targets" window doesn't scroll

### ISSUE THREAD

**Issue by tgrey1** [csound/web-ide#98]
In a project with multiple csds, when configuring targets the window needs the ability to scroll.  On a smaller screen laptop, adding a third target required fullscreen mode, and adding a fourth is impossible.

![image](https://user-images.githubusercontent.com/8214623/85081063-ea2a2f80-b198-11ea-9938-62a8049d1d91.png)

**Comment by csounder** [comment]
I agree!  It's difficult.  

I would add that there need to be an option a checkbox ? That allows the current selected .csd to be the default target

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music
